# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.20
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: true
odoo_test_flavor: Odoo
odoo_version: 17.0
org_name: Osynx Solutions
org_slug: Osynx Solutions
rebel_module_groups: []
repo_description: PH Payroll for Odoo Enterprise
repo_name: ''
repo_slug: ''
repo_website: https://osynx-solutions.odoo.com
use_pyproject_toml: false
use_ruff: false

