{
    "name": "Studio customizations",
    "version": "17.0.1.0",
    "category": "Studio",
    "description": """
This module has been generated by Odoo Studio.
It contains the apps created with Studio and the customizations of existing apps.
""",
    "author": "Vesta Automation Inc.",
    "depends": [
        "base",
        "contacts",
        "documents",
        "product",
        "project",
        "sale_management",
        "sales_team",
        "stock",
        "purchase",
        "web_studio",
    ],
    "data": [
        "data/ir_model.xml",
        "data/ir_model_fields.xml",
        "data/ir_ui_view.xml",
        # 'data/ir_actions_act_window.xml',
        # 'data/ir_actions_server.xml',
        # 'data/ir_ui_menu.xml',
        # 'data/base_automation.xml',
        # 'data/ir_model_access.xml',
        # 'data/ir_default.xml',
        # 'data/studio_approval_rule.xml',
    ],
    "application": False,
    "license": "OPL-1",
}
